// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbN5WP1JlSCutypEgMZQMDXC0HB1e47CE',
    appId: '1:43478840318:web:f3b9dade143c82beb046af',
    messagingSenderId: '43478840318',
    projectId: 'chat-app-f9cc1',
    authDomain: 'chat-app-f9cc1.firebaseapp.com',
    storageBucket: 'chat-app-f9cc1.firebasestorage.app',
    measurementId: 'G-Q6FFZDR7GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiechHD8SX02AE0tEwh92Nr02qY5djr7g',
    appId: '1:43478840318:android:d4cc27bf1c4c956ab046af',
    messagingSenderId: '43478840318',
    projectId: 'chat-app-f9cc1',
    storageBucket: 'chat-app-f9cc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKXJbpwW9c3nd-bWrC88P3UQr5xTyH4Dw',
    appId: '1:43478840318:ios:ad045a849aeca253b046af',
    messagingSenderId: '43478840318',
    projectId: 'chat-app-f9cc1',
    storageBucket: 'chat-app-f9cc1.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKXJbpwW9c3nd-bWrC88P3UQr5xTyH4Dw',
    appId: '1:43478840318:ios:ad045a849aeca253b046af',
    messagingSenderId: '43478840318',
    projectId: 'chat-app-f9cc1',
    storageBucket: 'chat-app-f9cc1.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbN5WP1JlSCutypEgMZQMDXC0HB1e47CE',
    appId: '1:43478840318:web:8071b0eb30036827b046af',
    messagingSenderId: '43478840318',
    projectId: 'chat-app-f9cc1',
    authDomain: 'chat-app-f9cc1.firebaseapp.com',
    storageBucket: 'chat-app-f9cc1.firebasestorage.app',
    measurementId: 'G-VEQL7SKDCG',
  );
}
